// system_mm_interconnect_0_monitor_system_console_master_mm_interconnect_0.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 17.1 590

`timescale 1 ps / 1 ps
module system_mm_interconnect_0_monitor_system_console_master_mm_interconnect_0 (
		input  wire        clk_clk_clk,                                //                              clk_clk.clk
		input  wire        gatherer_reset_reset_bridge_in_reset_reset, // gatherer_reset_reset_bridge_in_reset.reset
		input  wire [3:0]  gatherer_data_address,                      //                        gatherer_data.address
		output wire        gatherer_data_waitrequest,                  //                                     .waitrequest
		input  wire [3:0]  gatherer_data_byteenable,                   //                                     .byteenable
		input  wire        gatherer_data_read,                         //                                     .read
		output wire [31:0] gatherer_data_readdata,                     //                                     .readdata
		output wire        gatherer_data_readdatavalid,                //                                     .readdatavalid
		output wire [1:0]  pm_data_address,                            //                              pm_data.address
		output wire        pm_data_read,                               //                                     .read
		input  wire [31:0] pm_data_readdata,                           //                                     .readdata
		input  wire        pm_data_waitrequest                         //                                     .waitrequest
	);

	wire         gatherer_data_translator_avalon_universal_master_0_waitrequest;   // pm_data_translator:uav_waitrequest -> gatherer_data_translator:uav_waitrequest
	wire  [31:0] gatherer_data_translator_avalon_universal_master_0_readdata;      // pm_data_translator:uav_readdata -> gatherer_data_translator:uav_readdata
	wire         gatherer_data_translator_avalon_universal_master_0_debugaccess;   // gatherer_data_translator:uav_debugaccess -> pm_data_translator:uav_debugaccess
	wire   [3:0] gatherer_data_translator_avalon_universal_master_0_address;       // gatherer_data_translator:uav_address -> pm_data_translator:uav_address
	wire         gatherer_data_translator_avalon_universal_master_0_read;          // gatherer_data_translator:uav_read -> pm_data_translator:uav_read
	wire   [3:0] gatherer_data_translator_avalon_universal_master_0_byteenable;    // gatherer_data_translator:uav_byteenable -> pm_data_translator:uav_byteenable
	wire         gatherer_data_translator_avalon_universal_master_0_readdatavalid; // pm_data_translator:uav_readdatavalid -> gatherer_data_translator:uav_readdatavalid
	wire         gatherer_data_translator_avalon_universal_master_0_lock;          // gatherer_data_translator:uav_lock -> pm_data_translator:uav_lock
	wire         gatherer_data_translator_avalon_universal_master_0_write;         // gatherer_data_translator:uav_write -> pm_data_translator:uav_write
	wire  [31:0] gatherer_data_translator_avalon_universal_master_0_writedata;     // gatherer_data_translator:uav_writedata -> pm_data_translator:uav_writedata
	wire   [2:0] gatherer_data_translator_avalon_universal_master_0_burstcount;    // gatherer_data_translator:uav_burstcount -> pm_data_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (4),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (4),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (0),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) gatherer_data_translator (
		.clk                    (clk_clk_clk),                                                      //                       clk.clk
		.reset                  (gatherer_reset_reset_bridge_in_reset_reset),                       //                     reset.reset
		.uav_address            (gatherer_data_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (gatherer_data_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (gatherer_data_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (gatherer_data_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (gatherer_data_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (gatherer_data_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (gatherer_data_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (gatherer_data_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (gatherer_data_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (gatherer_data_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (gatherer_data_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (gatherer_data_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (gatherer_data_waitrequest),                                        //                          .waitrequest
		.av_byteenable          (gatherer_data_byteenable),                                         //                          .byteenable
		.av_read                (gatherer_data_read),                                               //                          .read
		.av_readdata            (gatherer_data_readdata),                                           //                          .readdata
		.av_readdatavalid       (gatherer_data_readdatavalid),                                      //                          .readdatavalid
		.av_burstcount          (1'b1),                                                             //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                             //               (terminated)
		.av_begintransfer       (1'b0),                                                             //               (terminated)
		.av_chipselect          (1'b0),                                                             //               (terminated)
		.av_write               (1'b0),                                                             //               (terminated)
		.av_writedata           (32'b00000000000000000000000000000000),                             //               (terminated)
		.av_lock                (1'b0),                                                             //               (terminated)
		.av_debugaccess         (1'b0),                                                             //               (terminated)
		.uav_clken              (),                                                                 //               (terminated)
		.av_clken               (1'b1),                                                             //               (terminated)
		.uav_response           (2'b00),                                                            //               (terminated)
		.av_response            (),                                                                 //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                             //               (terminated)
		.av_writeresponsevalid  ()                                                                  //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (2),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (4),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) pm_data_translator (
		.clk                    (clk_clk_clk),                                                      //                      clk.clk
		.reset                  (gatherer_reset_reset_bridge_in_reset_reset),                       //                    reset.reset
		.uav_address            (gatherer_data_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (gatherer_data_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (gatherer_data_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (gatherer_data_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (gatherer_data_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (gatherer_data_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (gatherer_data_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (gatherer_data_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (gatherer_data_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (gatherer_data_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (gatherer_data_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (pm_data_address),                                                  //      avalon_anti_slave_0.address
		.av_read                (pm_data_read),                                                     //                         .read
		.av_readdata            (pm_data_readdata),                                                 //                         .readdata
		.av_waitrequest         (pm_data_waitrequest),                                              //                         .waitrequest
		.av_write               (),                                                                 //              (terminated)
		.av_writedata           (),                                                                 //              (terminated)
		.av_begintransfer       (),                                                                 //              (terminated)
		.av_beginbursttransfer  (),                                                                 //              (terminated)
		.av_burstcount          (),                                                                 //              (terminated)
		.av_byteenable          (),                                                                 //              (terminated)
		.av_readdatavalid       (1'b0),                                                             //              (terminated)
		.av_writebyteenable     (),                                                                 //              (terminated)
		.av_lock                (),                                                                 //              (terminated)
		.av_chipselect          (),                                                                 //              (terminated)
		.av_clken               (),                                                                 //              (terminated)
		.uav_clken              (1'b0),                                                             //              (terminated)
		.av_debugaccess         (),                                                                 //              (terminated)
		.av_outputenable        (),                                                                 //              (terminated)
		.uav_response           (),                                                                 //              (terminated)
		.av_response            (2'b00),                                                            //              (terminated)
		.uav_writeresponsevalid (),                                                                 //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                              //              (terminated)
	);

endmodule
