	soc_system_v4 u0 (
		.adc_fifo_in_data                          (<connected-to-adc_fifo_in_data>),                          //                 adc_fifo_in.data
		.adc_fifo_in_valid                         (<connected-to-adc_fifo_in_valid>),                         //                            .valid
		.adc_fifo_in_ready                         (<connected-to-adc_fifo_in_ready>),                         //                            .ready
		.adc_val_sub_export                        (<connected-to-adc_val_sub_export>),                        //                 adc_val_sub.export
		.alt_vip_itc_0_clocked_video_vid_clk       (<connected-to-alt_vip_itc_0_clocked_video_vid_clk>),       // alt_vip_itc_0_clocked_video.vid_clk
		.alt_vip_itc_0_clocked_video_vid_data      (<connected-to-alt_vip_itc_0_clocked_video_vid_data>),      //                            .vid_data
		.alt_vip_itc_0_clocked_video_underflow     (<connected-to-alt_vip_itc_0_clocked_video_underflow>),     //                            .underflow
		.alt_vip_itc_0_clocked_video_vid_datavalid (<connected-to-alt_vip_itc_0_clocked_video_vid_datavalid>), //                            .vid_datavalid
		.alt_vip_itc_0_clocked_video_vid_v_sync    (<connected-to-alt_vip_itc_0_clocked_video_vid_v_sync>),    //                            .vid_v_sync
		.alt_vip_itc_0_clocked_video_vid_h_sync    (<connected-to-alt_vip_itc_0_clocked_video_vid_h_sync>),    //                            .vid_h_sync
		.alt_vip_itc_0_clocked_video_vid_f         (<connected-to-alt_vip_itc_0_clocked_video_vid_f>),         //                            .vid_f
		.alt_vip_itc_0_clocked_video_vid_h         (<connected-to-alt_vip_itc_0_clocked_video_vid_h>),         //                            .vid_h
		.alt_vip_itc_0_clocked_video_vid_v         (<connected-to-alt_vip_itc_0_clocked_video_vid_v>),         //                            .vid_v
		.analyzer_pll_locked_export                (<connected-to-analyzer_pll_locked_export>),                //         analyzer_pll_locked.export
		.analyzer_pll_outclk0_clk                  (<connected-to-analyzer_pll_outclk0_clk>),                  //        analyzer_pll_outclk0.clk
		.analyzer_pll_outclk1_clk                  (<connected-to-analyzer_pll_outclk1_clk>),                  //        analyzer_pll_outclk1.clk
		.analyzer_pll_outclk2_clk                  (<connected-to-analyzer_pll_outclk2_clk>),                  //        analyzer_pll_outclk2.clk
		.analyzer_pll_outclk3_clk                  (<connected-to-analyzer_pll_outclk3_clk>),                  //        analyzer_pll_outclk3.clk
		.analyzer_pll_reset_reset                  (<connected-to-analyzer_pll_reset_reset>),                  //          analyzer_pll_reset.reset
		.aux_cnt_out_export                        (<connected-to-aux_cnt_out_export>),                        //                 aux_cnt_out.export
		.clk_clk                                   (<connected-to-clk_clk>),                                   //                         clk.clk
		.ctrl_in_export                            (<connected-to-ctrl_in_export>),                            //                     ctrl_in.export
		.ctrl_out_export                           (<connected-to-ctrl_out_export>),                           //                    ctrl_out.export
		.dac_preamp_MISO                           (<connected-to-dac_preamp_MISO>),                           //                  dac_preamp.MISO
		.dac_preamp_MOSI                           (<connected-to-dac_preamp_MOSI>),                           //                            .MOSI
		.dac_preamp_SCLK                           (<connected-to-dac_preamp_SCLK>),                           //                            .SCLK
		.dac_preamp_SS_n                           (<connected-to-dac_preamp_SS_n>),                           //                            .SS_n
		.dconv_fifo_in_data                        (<connected-to-dconv_fifo_in_data>),                        //               dconv_fifo_in.data
		.dconv_fifo_in_valid                       (<connected-to-dconv_fifo_in_valid>),                       //                            .valid
		.dconv_fifo_in_ready                       (<connected-to-dconv_fifo_in_ready>),                       //                            .ready
		.dconv_fifo_q_in_data                      (<connected-to-dconv_fifo_q_in_data>),                      //             dconv_fifo_q_in.data
		.dconv_fifo_q_in_valid                     (<connected-to-dconv_fifo_q_in_valid>),                     //                            .valid
		.dconv_fifo_q_in_ready                     (<connected-to-dconv_fifo_q_in_ready>),                     //                            .ready
		.dconv_fir_in_data                         (<connected-to-dconv_fir_in_data>),                         //                dconv_fir_in.data
		.dconv_fir_in_valid                        (<connected-to-dconv_fir_in_valid>),                        //                            .valid
		.dconv_fir_in_error                        (<connected-to-dconv_fir_in_error>),                        //                            .error
		.dconv_fir_out_data                        (<connected-to-dconv_fir_out_data>),                        //               dconv_fir_out.data
		.dconv_fir_out_valid                       (<connected-to-dconv_fir_out_valid>),                       //                            .valid
		.dconv_fir_out_error                       (<connected-to-dconv_fir_out_error>),                       //                            .error
		.dconv_fir_q_in_data                       (<connected-to-dconv_fir_q_in_data>),                       //              dconv_fir_q_in.data
		.dconv_fir_q_in_valid                      (<connected-to-dconv_fir_q_in_valid>),                      //                            .valid
		.dconv_fir_q_in_error                      (<connected-to-dconv_fir_q_in_error>),                      //                            .error
		.dconv_fir_q_out_data                      (<connected-to-dconv_fir_q_out_data>),                      //             dconv_fir_q_out.data
		.dconv_fir_q_out_valid                     (<connected-to-dconv_fir_q_out_valid>),                     //                            .valid
		.dconv_fir_q_out_error                     (<connected-to-dconv_fir_q_out_error>),                     //                            .error
		.delay_nosig_export                        (<connected-to-delay_nosig_export>),                        //                 delay_nosig.export
		.delay_sig_export                          (<connected-to-delay_sig_export>),                          //                   delay_sig.export
		.delay_t1_export                           (<connected-to-delay_t1_export>),                           //                    delay_t1.export
		.echoes_per_scan_export                    (<connected-to-echoes_per_scan_export>),                    //             echoes_per_scan.export
		.fifo_clk_bridge_in_clk                    (<connected-to-fifo_clk_bridge_in_clk>),                    //          fifo_clk_bridge_in.clk
		.fifo_rst_reset                            (<connected-to-fifo_rst_reset>),                            //                    fifo_rst.reset
		.hps_0_h2f_reset_reset_n                   (<connected-to-hps_0_h2f_reset_reset_n>),                   //             hps_0_h2f_reset.reset_n
		.hps_0_hps_io_hps_io_emac1_inst_TX_CLK     (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TX_CLK>),     //                hps_0_hps_io.hps_io_emac1_inst_TX_CLK
		.hps_0_hps_io_hps_io_emac1_inst_TXD0       (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD0>),       //                            .hps_io_emac1_inst_TXD0
		.hps_0_hps_io_hps_io_emac1_inst_TXD1       (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD1>),       //                            .hps_io_emac1_inst_TXD1
		.hps_0_hps_io_hps_io_emac1_inst_TXD2       (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD2>),       //                            .hps_io_emac1_inst_TXD2
		.hps_0_hps_io_hps_io_emac1_inst_TXD3       (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD3>),       //                            .hps_io_emac1_inst_TXD3
		.hps_0_hps_io_hps_io_emac1_inst_RXD0       (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD0>),       //                            .hps_io_emac1_inst_RXD0
		.hps_0_hps_io_hps_io_emac1_inst_MDIO       (<connected-to-hps_0_hps_io_hps_io_emac1_inst_MDIO>),       //                            .hps_io_emac1_inst_MDIO
		.hps_0_hps_io_hps_io_emac1_inst_MDC        (<connected-to-hps_0_hps_io_hps_io_emac1_inst_MDC>),        //                            .hps_io_emac1_inst_MDC
		.hps_0_hps_io_hps_io_emac1_inst_RX_CTL     (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RX_CTL>),     //                            .hps_io_emac1_inst_RX_CTL
		.hps_0_hps_io_hps_io_emac1_inst_TX_CTL     (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TX_CTL>),     //                            .hps_io_emac1_inst_TX_CTL
		.hps_0_hps_io_hps_io_emac1_inst_RX_CLK     (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RX_CLK>),     //                            .hps_io_emac1_inst_RX_CLK
		.hps_0_hps_io_hps_io_emac1_inst_RXD1       (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD1>),       //                            .hps_io_emac1_inst_RXD1
		.hps_0_hps_io_hps_io_emac1_inst_RXD2       (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD2>),       //                            .hps_io_emac1_inst_RXD2
		.hps_0_hps_io_hps_io_emac1_inst_RXD3       (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD3>),       //                            .hps_io_emac1_inst_RXD3
		.hps_0_hps_io_hps_io_qspi_inst_IO0         (<connected-to-hps_0_hps_io_hps_io_qspi_inst_IO0>),         //                            .hps_io_qspi_inst_IO0
		.hps_0_hps_io_hps_io_qspi_inst_IO1         (<connected-to-hps_0_hps_io_hps_io_qspi_inst_IO1>),         //                            .hps_io_qspi_inst_IO1
		.hps_0_hps_io_hps_io_qspi_inst_IO2         (<connected-to-hps_0_hps_io_hps_io_qspi_inst_IO2>),         //                            .hps_io_qspi_inst_IO2
		.hps_0_hps_io_hps_io_qspi_inst_IO3         (<connected-to-hps_0_hps_io_hps_io_qspi_inst_IO3>),         //                            .hps_io_qspi_inst_IO3
		.hps_0_hps_io_hps_io_qspi_inst_SS0         (<connected-to-hps_0_hps_io_hps_io_qspi_inst_SS0>),         //                            .hps_io_qspi_inst_SS0
		.hps_0_hps_io_hps_io_qspi_inst_CLK         (<connected-to-hps_0_hps_io_hps_io_qspi_inst_CLK>),         //                            .hps_io_qspi_inst_CLK
		.hps_0_hps_io_hps_io_sdio_inst_CMD         (<connected-to-hps_0_hps_io_hps_io_sdio_inst_CMD>),         //                            .hps_io_sdio_inst_CMD
		.hps_0_hps_io_hps_io_sdio_inst_D0          (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D0>),          //                            .hps_io_sdio_inst_D0
		.hps_0_hps_io_hps_io_sdio_inst_D1          (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D1>),          //                            .hps_io_sdio_inst_D1
		.hps_0_hps_io_hps_io_sdio_inst_CLK         (<connected-to-hps_0_hps_io_hps_io_sdio_inst_CLK>),         //                            .hps_io_sdio_inst_CLK
		.hps_0_hps_io_hps_io_sdio_inst_D2          (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D2>),          //                            .hps_io_sdio_inst_D2
		.hps_0_hps_io_hps_io_sdio_inst_D3          (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D3>),          //                            .hps_io_sdio_inst_D3
		.hps_0_hps_io_hps_io_usb1_inst_D0          (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D0>),          //                            .hps_io_usb1_inst_D0
		.hps_0_hps_io_hps_io_usb1_inst_D1          (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D1>),          //                            .hps_io_usb1_inst_D1
		.hps_0_hps_io_hps_io_usb1_inst_D2          (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D2>),          //                            .hps_io_usb1_inst_D2
		.hps_0_hps_io_hps_io_usb1_inst_D3          (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D3>),          //                            .hps_io_usb1_inst_D3
		.hps_0_hps_io_hps_io_usb1_inst_D4          (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D4>),          //                            .hps_io_usb1_inst_D4
		.hps_0_hps_io_hps_io_usb1_inst_D5          (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D5>),          //                            .hps_io_usb1_inst_D5
		.hps_0_hps_io_hps_io_usb1_inst_D6          (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D6>),          //                            .hps_io_usb1_inst_D6
		.hps_0_hps_io_hps_io_usb1_inst_D7          (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D7>),          //                            .hps_io_usb1_inst_D7
		.hps_0_hps_io_hps_io_usb1_inst_CLK         (<connected-to-hps_0_hps_io_hps_io_usb1_inst_CLK>),         //                            .hps_io_usb1_inst_CLK
		.hps_0_hps_io_hps_io_usb1_inst_STP         (<connected-to-hps_0_hps_io_hps_io_usb1_inst_STP>),         //                            .hps_io_usb1_inst_STP
		.hps_0_hps_io_hps_io_usb1_inst_DIR         (<connected-to-hps_0_hps_io_hps_io_usb1_inst_DIR>),         //                            .hps_io_usb1_inst_DIR
		.hps_0_hps_io_hps_io_usb1_inst_NXT         (<connected-to-hps_0_hps_io_hps_io_usb1_inst_NXT>),         //                            .hps_io_usb1_inst_NXT
		.hps_0_hps_io_hps_io_spim1_inst_CLK        (<connected-to-hps_0_hps_io_hps_io_spim1_inst_CLK>),        //                            .hps_io_spim1_inst_CLK
		.hps_0_hps_io_hps_io_spim1_inst_MOSI       (<connected-to-hps_0_hps_io_hps_io_spim1_inst_MOSI>),       //                            .hps_io_spim1_inst_MOSI
		.hps_0_hps_io_hps_io_spim1_inst_MISO       (<connected-to-hps_0_hps_io_hps_io_spim1_inst_MISO>),       //                            .hps_io_spim1_inst_MISO
		.hps_0_hps_io_hps_io_spim1_inst_SS0        (<connected-to-hps_0_hps_io_hps_io_spim1_inst_SS0>),        //                            .hps_io_spim1_inst_SS0
		.hps_0_hps_io_hps_io_uart0_inst_RX         (<connected-to-hps_0_hps_io_hps_io_uart0_inst_RX>),         //                            .hps_io_uart0_inst_RX
		.hps_0_hps_io_hps_io_uart0_inst_TX         (<connected-to-hps_0_hps_io_hps_io_uart0_inst_TX>),         //                            .hps_io_uart0_inst_TX
		.hps_0_hps_io_hps_io_i2c0_inst_SDA         (<connected-to-hps_0_hps_io_hps_io_i2c0_inst_SDA>),         //                            .hps_io_i2c0_inst_SDA
		.hps_0_hps_io_hps_io_i2c0_inst_SCL         (<connected-to-hps_0_hps_io_hps_io_i2c0_inst_SCL>),         //                            .hps_io_i2c0_inst_SCL
		.hps_0_hps_io_hps_io_i2c1_inst_SDA         (<connected-to-hps_0_hps_io_hps_io_i2c1_inst_SDA>),         //                            .hps_io_i2c1_inst_SDA
		.hps_0_hps_io_hps_io_i2c1_inst_SCL         (<connected-to-hps_0_hps_io_hps_io_i2c1_inst_SCL>),         //                            .hps_io_i2c1_inst_SCL
		.hps_0_hps_io_hps_io_gpio_inst_GPIO09      (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO09>),      //                            .hps_io_gpio_inst_GPIO09
		.hps_0_hps_io_hps_io_gpio_inst_GPIO35      (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO35>),      //                            .hps_io_gpio_inst_GPIO35
		.hps_0_hps_io_hps_io_gpio_inst_GPIO40      (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO40>),      //                            .hps_io_gpio_inst_GPIO40
		.hps_0_hps_io_hps_io_gpio_inst_GPIO48      (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO48>),      //                            .hps_io_gpio_inst_GPIO48
		.hps_0_hps_io_hps_io_gpio_inst_GPIO53      (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO53>),      //                            .hps_io_gpio_inst_GPIO53
		.hps_0_hps_io_hps_io_gpio_inst_GPIO54      (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO54>),      //                            .hps_io_gpio_inst_GPIO54
		.hps_0_hps_io_hps_io_gpio_inst_GPIO61      (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO61>),      //                            .hps_io_gpio_inst_GPIO61
		.i2c_ext_sda_in                            (<connected-to-i2c_ext_sda_in>),                            //                     i2c_ext.sda_in
		.i2c_ext_scl_in                            (<connected-to-i2c_ext_scl_in>),                            //                            .scl_in
		.i2c_ext_sda_oe                            (<connected-to-i2c_ext_sda_oe>),                            //                            .sda_oe
		.i2c_ext_scl_oe                            (<connected-to-i2c_ext_scl_oe>),                            //                            .scl_oe
		.i2c_int_sda_in                            (<connected-to-i2c_int_sda_in>),                            //                     i2c_int.sda_in
		.i2c_int_scl_in                            (<connected-to-i2c_int_scl_in>),                            //                            .scl_in
		.i2c_int_sda_oe                            (<connected-to-i2c_int_sda_oe>),                            //                            .sda_oe
		.i2c_int_scl_oe                            (<connected-to-i2c_int_scl_oe>),                            //                            .scl_oe
		.init_delay_export                         (<connected-to-init_delay_export>),                         //                  init_delay.export
		.memory_mem_a                              (<connected-to-memory_mem_a>),                              //                      memory.mem_a
		.memory_mem_ba                             (<connected-to-memory_mem_ba>),                             //                            .mem_ba
		.memory_mem_ck                             (<connected-to-memory_mem_ck>),                             //                            .mem_ck
		.memory_mem_ck_n                           (<connected-to-memory_mem_ck_n>),                           //                            .mem_ck_n
		.memory_mem_cke                            (<connected-to-memory_mem_cke>),                            //                            .mem_cke
		.memory_mem_cs_n                           (<connected-to-memory_mem_cs_n>),                           //                            .mem_cs_n
		.memory_mem_ras_n                          (<connected-to-memory_mem_ras_n>),                          //                            .mem_ras_n
		.memory_mem_cas_n                          (<connected-to-memory_mem_cas_n>),                          //                            .mem_cas_n
		.memory_mem_we_n                           (<connected-to-memory_mem_we_n>),                           //                            .mem_we_n
		.memory_mem_reset_n                        (<connected-to-memory_mem_reset_n>),                        //                            .mem_reset_n
		.memory_mem_dq                             (<connected-to-memory_mem_dq>),                             //                            .mem_dq
		.memory_mem_dqs                            (<connected-to-memory_mem_dqs>),                            //                            .mem_dqs
		.memory_mem_dqs_n                          (<connected-to-memory_mem_dqs_n>),                          //                            .mem_dqs_n
		.memory_mem_odt                            (<connected-to-memory_mem_odt>),                            //                            .mem_odt
		.memory_mem_dm                             (<connected-to-memory_mem_dm>),                             //                            .mem_dm
		.memory_oct_rzqin                          (<connected-to-memory_oct_rzqin>),                          //                            .oct_rzqin
		.nmr_sys_pll_locked_export                 (<connected-to-nmr_sys_pll_locked_export>),                 //          nmr_sys_pll_locked.export
		.nmr_sys_pll_outclk_clk                    (<connected-to-nmr_sys_pll_outclk_clk>),                    //          nmr_sys_pll_outclk.clk
		.nmr_sys_pll_reset_reset                   (<connected-to-nmr_sys_pll_reset_reset>),                   //           nmr_sys_pll_reset.reset
		.pll_vga_clk65_clk                         (<connected-to-pll_vga_clk65_clk>),                         //               pll_vga_clk65.clk
		.pll_vga_locked_export                     (<connected-to-pll_vga_locked_export>),                     //              pll_vga_locked.export
		.pulse_180deg_export                       (<connected-to-pulse_180deg_export>),                       //                pulse_180deg.export
		.pulse_90deg_export                        (<connected-to-pulse_90deg_export>),                        //                 pulse_90deg.export
		.pulse_t1_export                           (<connected-to-pulse_t1_export>),                           //                    pulse_t1.export
		.reset_reset_n                             (<connected-to-reset_reset_n>),                             //                       reset.reset_n
		.rx_delay_export                           (<connected-to-rx_delay_export>),                           //                    rx_delay.export
		.samples_per_echo_export                   (<connected-to-samples_per_echo_export>),                   //            samples_per_echo.export
		.sdram_clk_clk                             (<connected-to-sdram_clk_clk>),                             //                   sdram_clk.clk
		.sdram_wire_addr                           (<connected-to-sdram_wire_addr>),                           //                  sdram_wire.addr
		.sdram_wire_ba                             (<connected-to-sdram_wire_ba>),                             //                            .ba
		.sdram_wire_cas_n                          (<connected-to-sdram_wire_cas_n>),                          //                            .cas_n
		.sdram_wire_cke                            (<connected-to-sdram_wire_cke>),                            //                            .cke
		.sdram_wire_cs_n                           (<connected-to-sdram_wire_cs_n>),                           //                            .cs_n
		.sdram_wire_dq                             (<connected-to-sdram_wire_dq>),                             //                            .dq
		.sdram_wire_dqm                            (<connected-to-sdram_wire_dqm>),                            //                            .dqm
		.sdram_wire_ras_n                          (<connected-to-sdram_wire_ras_n>),                          //                            .ras_n
		.sdram_wire_we_n                           (<connected-to-sdram_wire_we_n>),                           //                            .we_n
		.spi_mtch_ntwrk_MISO                       (<connected-to-spi_mtch_ntwrk_MISO>),                       //              spi_mtch_ntwrk.MISO
		.spi_mtch_ntwrk_MOSI                       (<connected-to-spi_mtch_ntwrk_MOSI>),                       //                            .MOSI
		.spi_mtch_ntwrk_SCLK                       (<connected-to-spi_mtch_ntwrk_SCLK>),                       //                            .SCLK
		.spi_mtch_ntwrk_SS_n                       (<connected-to-spi_mtch_ntwrk_SS_n>),                       //                            .SS_n
		.switches_export                           (<connected-to-switches_export>)                            //                    switches.export
	);

