function compute_t1_p180_sw(path,en_fig)
    %path : directory path to the samples
    % enable_figure : enable the figure generated by compute_single
    
    %% SETTINGS
    reprocess_basic_op = 0; % reprocess basic operation of the data for basic plotting
    plottype = 1;

    %% BASIC PROGRAM
    if exist ([path,'\processed_data.mat'],'file') && ~reprocess_basic_op % check if this computation has been done before
        load([path,'\processed_data.mat']);
    else

        tE = read_custom_acqu_par(path,'echoTimeRun');
        NoE = read_custom_acqu_par(path,'nrEchoes');
        Df = read_custom_acqu_par(path,'b1Freq')*1e6;
        Sf = read_custom_acqu_par(path,'adcFreq')*1e6;
        start_param = read_custom_acqu_par(path,'minP180t1');
        stop_param = read_custom_acqu_par(path,'maxP180t1');
        nsteps = read_custom_acqu_par(path,'p180t1steps');
        logspaceyesno = read_custom_acqu_par(path,'logspace');

        if (logspaceyesno)
            sweep_param = logspace(log10(start_param),log10(stop_param),nsteps);
        else
            sweep_param = linspace(start_param,stop_param,nsteps);
        end
        
        % this is a standard butterworth filter used by downconverter (downconvert.m)
        % it is implemented here because it takes forever to compute it, and
        % the downconverter is called thousand times depending on the data
        n = 3; Wn = 0.008;
        [butter_b,butter_a] = butter(n,Wn);
        a = zeros(length(sweep_param),NoE);
        a_init = zeros(1,length(sweep_param));
        a_avg = zeros(1,length(sweep_param));
        for m = 1:length(sweep_param)
            disp(['current t1 180-pulse: ',num2str(sweep_param(m)),'us']);
            filename = ['\dat_',num2str(sweep_param(m),'%03.3f')];
            [a(m,:),a_init(m),a_avg(m)] = compute_multiple(path,filename,Df,Sf,tE,en_fig, butter_a, butter_b);
        end

        save([path,'\processed_data'],'a','a_init','a_avg','sweep_param'); % save processed data
        
    end
    
    %% PLOT OPTIONS
    if plottype == 0
        figure(171);
        plot(sweep_param,snr);
        title('Signal-to-noise ratio'); set(gca,'FontSize',12);
        xlabel('90 degrees pulse length (\mus)');
        ylabel('SNR');

        figure(172);
        plot(sweep_param,sum(real(a')));
        title('Echo average with pulse length'); set(gca,'FontSize',12);
        xlabel('90 degrees pulse length (\mus)');
        ylabel('Amplitude');

        figure(173);
        plot(sweep_param,a_init);
        title('Initial signal with pulse length'); set(gca,'FontSize',12);
        xlabel('90 degrees pulse (\mus)');
        ylabel('Amplitude');
    
        figure(174);
        plot(sweep_param,a_avg);
        title('Real signal amplitude'); set(gca,'FontSize',12);
        xlabel('90 degrees pulse (\mus)');
        ylabel('Amplitude');
    
    else
            
        % curve fit
        fittype = 'poly5';
        [v_curve,~,v_output]=fit(sweep_param',sum(real(a'))',fittype);
        [a_curve,~,a_output]=fit(sweep_param',a_init',fittype);
        [s_curve,~,s_output]=fit(sweep_param',a_avg',fittype);

        figure(172);
        subplot(2,1,1); hold on;
        plot(sweep_param,sum(real(a')));
        plot(v_curve,sweep_param,sum(real(a')));
        title('Vector signal amplitude');
        xlabel('90 degrees pulse (\mus)');
        ylabel('Amplitude');
        subplot(2,1,2);
        hist(v_output.residuals);
        title('Residual');
        xlabel('\Delta A');
        ylabel('Amplitude');  

        figure(173);
        subplot(2,1,1); hold on;
        plot(sweep_param,a_init);
        plot(a_curve,sweep_param,a_init);
        title('Initial signal amplitude');
        xlabel('90 degrees pulse (\mus)');
        ylabel('Amplitude');
        subplot(2,1,2);
        hist(a_output.residuals);
        title('Residual');
        xlabel('\Delta A');
        ylabel('Amplitude');

        figure(174);
        subplot(2,1,1); hold on;
        plot(sweep_param,a_avg);
        plot(s_curve,sweep_param,a_avg);
        title('Real signal amplitude');
        xlabel('90 degrees pulse (\mus)');
        ylabel('Amplitude');
        subplot(2,1,2);
        hist(s_output.residuals);
        title('Residual');
        xlabel('\Delta A');
        ylabel('Amplitude');
    
    end
end