transcript on
if {[file exists rtl_work]} {
	vdel -lib rtl_work -all
}
vlib rtl_work
vmap work rtl_work

vlog -vlog01compat -work work +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-NoSoC/HDL {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-NoSoC/HDL/NMR_PULSE_PROGRAM.v}
vlog -vlog01compat -work work +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-NoSoC/HDL {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-NoSoC/HDL/NMR_Controller.v}
vlog -vlog01compat -work work +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-NoSoC/HDL {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-NoSoC/HDL/CDC_Input_Synchronizer.v}
vlog -vlog01compat -work work +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-NoSoC/HDL {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-NoSoC/HDL/ADC_LTC1746_DRV.v}
vlog -vlog01compat -work work +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-NoSoC/HDL {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-NoSoC/HDL/ADC_ACQ_WINGEN.v}
vlog -vlog01compat -work work +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-NoSoC/HDL/ALTERA_IPs {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-NoSoC/HDL/ALTERA_IPs/altiobuf.v}
vlog -vlog01compat -work work +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/DE1_SOC_Linux_FB.v}
vlib vga_pll
vmap vga_pll vga_pll
vlog -vlog01compat -work vga_pll +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_verilog/altera_IPs/vga_pll/vga_pll {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_verilog/altera_IPs/vga_pll/vga_pll/vga_pll_0002.v}
vlib soc_system
vmap soc_system soc_system
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/soc_system.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_reset_controller.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_reset_synchronizer.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_avalon_st_adapter.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_1.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_avalon_st_adapter_001.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_avalon_st_adapter.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_0.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_sysid_qsys.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_switches.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_sram_test_w2.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_sram_test_w1.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_sram_test_r.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_sdram.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_nmr_sys_pll.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_nmr_parameters.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_nmr_parameters_samples_per_echo.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_nmr_parameters_delay_t1.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_nmr_parameters_delay_nosig.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_master_non_sec.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_avalon_packets_to_master.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_avalon_st_packets_to_bytes.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_avalon_st_bytes_to_packets.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_avalon_st_jtag_interface.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_jtag_dc_streaming.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_jtag_sld_node.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_jtag_streaming.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_avalon_st_idle_remover.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_avalon_st_idle_inserter.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_jtag_uart.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_avalon_i2c.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_avalon_i2c_csr.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_avalon_i2c_clk_cnt.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_avalon_i2c_condt_det.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_avalon_i2c_condt_gen.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_avalon_i2c_fifo.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_avalon_i2c_mstfsm.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_avalon_i2c_rxshifter.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_avalon_i2c_txshifter.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_avalon_i2c_spksupp.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_avalon_i2c_txout.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_hps_0.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_hps_0_hps_io.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/hps_sdram.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_mem_if_hhp_qseq_synth_top.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/hps_sdram_p0_acv_hard_addr_cmd_pads.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/hps_sdram_p0_acv_hard_io_pads.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/hps_sdram_p0_acv_hard_memphy.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/hps_sdram_p0_acv_ldc.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/hps_sdram_p0_altdqdqs.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/hps_sdram_p0_clock_pair_generator.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/hps_sdram_p0_generic_ddio.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_gp_pll.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_dma_test.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_dma_fifo.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_avalon_dc_fifo.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_dcfifo_synchronizer_bundle.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_dac_preamp.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_ctrl_out.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_ctrl_in.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_pll_reconfig_top.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_pll_reconfig_core.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_std_synchronizer.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_analyzer_pll.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/alt_vipvfr131_vfr.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/alt_vipvfr131_vfr_controller.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/alt_vipvfr131_vfr_control_packet_encoder.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/alt_vipvfr131_prc.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/alt_vipvfr131_prc_core.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/alt_vipvfr131_prc_read_master.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/alt_vipvfr131_common_avalon_mm_slave.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/alt_vipvfr131_common_stream_output.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/alt_vipitc131_IS2Vid_calculate_mode.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/alt_vipitc131_IS2Vid_control.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/alt_vipitc131_IS2Vid_statemachine.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/alt_vipitc131_common_fifo.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/alt_vipitc131_common_generic_count.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/alt_vipitc131_common_sync.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/alt_vipitc131_common_trigger_sync.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_adc_fifo_mem.v}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_avalon_st_adapter_timing_adapter_0.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_avalon_st_adapter_data_format_adapter_0.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_irq_mapper_001.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_irq_mapper.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_avalon_st_adapter_001_error_adapter_0.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_avalon_st_adapter_error_adapter_0.sv}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_avalon_st_handshake_clock_crosser.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_avalon_st_clock_crosser.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_avalon_st_pipeline_base.v}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_std_synchronizer_nocut.v}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_merlin_width_adapter.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_merlin_address_alignment.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_merlin_burst_uncompressor.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_rsp_mux_007.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_merlin_arbitrator.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_rsp_mux_005.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_rsp_mux_003.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_rsp_mux.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_rsp_demux_004.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_rsp_demux_002.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_rsp_demux.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_cmd_mux_023.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_cmd_mux_002.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_cmd_mux.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_cmd_demux_007.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_cmd_demux_006.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_cmd_demux_005.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_cmd_demux_003.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_cmd_demux.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_merlin_burst_adapter.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_merlin_burst_adapter_13_1.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_merlin_traffic_limiter.sv}
vlog -vlog01compat -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_avalon_sc_fifo.v}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_router_035.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_router_034.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_router_032.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_router_012.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_router_011.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_router_010.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_router_009.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_router_008.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_router_007.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_router_006.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_router_005.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_router_003.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_router_002.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_router.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_merlin_slave_agent.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_merlin_master_agent.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_merlin_axi_master_ni.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_merlin_slave_translator.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_merlin_master_translator.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_rsp_mux.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_cmd_mux.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_cmd_demux.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_router_002.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_router_001.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_router.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_merlin_axi_slave_ni.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_master_non_sec_p2b_adapter.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_master_non_sec_b2p_adapter.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_master_non_sec_timing_adt.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altdq_dqs2_acv_connect_to_hard_phy_cyclonev.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_mem_if_dll_cyclonev.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_mem_if_hard_memory_controller_top_cyclonev.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/altera_mem_if_oct_cyclonev.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/hps_sdram_p0.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/hps_sdram_pll.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_hps_0_hps_io_border.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/soc_system_hps_0_fpga_interfaces.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/alt_vipitc131_IS2Vid.sv}
vlog -sv -work soc_system +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/alt_vipitc131_IS2Vid_mode_banks.sv}
vcom -93 -work soc_system {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/alt_vipvfr131_common_package.vhd}
vcom -93 -work soc_system {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/alt_vipvfr131_common_one_bit_delay.vhd}
vcom -93 -work soc_system {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/alt_vipvfr131_common_avalon_mm_bursting_master_fifo.vhd}
vcom -93 -work soc_system {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/alt_vipvfr131_common_pulling_width_adapter.vhd}
vcom -93 -work soc_system {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/alt_vipvfr131_common_general_fifo.vhd}
vcom -93 -work soc_system {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/alt_vipvfr131_common_fifo_usedw_calculator.vhd}
vcom -93 -work soc_system {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/alt_vipvfr131_common_gray_clock_crosser.vhd}
vcom -93 -work soc_system {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/alt_vipvfr131_common_std_logic_vector_delay.vhd}
vcom -93 -work soc_system {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/alt_vipvfr131_common_logic_fifo.vhd}
vcom -93 -work soc_system {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_qsys/soc_system/synthesis/submodules/alt_vipvfr131_common_ram_fifo.vhd}

vlog -vlog01compat -work work +incdir+D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_modelsim/i2c_tca9555 {D:/NMR_Thesis_PCBv2_hdl_v1_2018/QUARTUS-SoC/CODE_modelsim/i2c_tca9555/i2c_tca9555_tb.v}

vsim -t 1ps -L altera_ver -L lpm_ver -L sgate_ver -L altera_mf_ver -L altera_lnsim_ver -L cyclonev_ver -L cyclonev_hssi_ver -L cyclonev_pcie_hip_ver -L rtl_work -L work -L vga_pll -L soc_system -voptargs="+acc"  i2c_tca9555_tb

add wave *
view structure
view signals
run 10 us
